### ISSUE TITLE
arte7dump.go:168: unable to find Arte+7 API url

### ISSUE THREAD

**Issue by pushf** [foutaise/arte7dump#1]
Thanks for this great tool i'm using for months from now !

Since the end of september 2016, arte7dump failed with le following message : 
arte7dump.go:168: unable to find Arte+7 API url

Arte has probably changed something in their page.
Hope it will not be too hard to update arte7dump.go !

**Comment by foutaise** [comment]
Thanks for your report, stay tuned, I'll investigate during the week-end.

**Comment by foutaise** [comment]
I've just committed a new release, including the possibility to choose the expected width. Have fun.

**Comment by remivoirin** [comment]
Wow... Fast.

**Comment by pushf** [comment]
Thanks, the new release works fine !
