### ISSUE TITLE
arte7dump.go:150: unable to find Arte+7 fr video 720 pixels wide

### ISSUE THREAD

**Issue by pushf** [foutaise/arte7dump#2]
Hi Foutaise,

Thanks for your great tool !

Since some days, Arte has probably made some changes, and I get the following message while trying to fetch an Arte+7 video :

arte7dump.go:150: unable to find Arte+7 fr video 720 pixels wide

while running arte7dump.go without cli parameters, and 

arte7dump.go:150: unable to find Arte+7 fr video 1280 pixels wide

while running arte7dump.go with '-w'  cli parameter.

I've got these messages with the following videos :

http://www.arte.tv/guide/fr/044202-001-A/charlemagne-1-3
http://www.arte.tv/guide/fr/044202-002-A/charlemagne-2-3
http://www.arte.tv/guide/fr/044202-003-A/charlemagne-3-3
and some other ones.

Thanks for your great tool !

**Comment by foutaise** [comment]
Hi pushf,

Please update your repo. I made an update a few days ago (cf commit 60c4a05).

Best regards,

**Comment by pushf** [comment]
After an svn up and go rebuild, ok, I can fetch the videos !
Thanks you for quick answer !

Best regards,
